from .main_page import MainPage
from .login_page import LoginPage

from pages.Users.manage_users_page import ManageUsersPage
from pages.Users.create_user_page import CreateUserPage
from pages.Users.update_user_profile_details_page import UpdateUserProfileDetailsPage
from pages.Users.update_user_account_details_page import UpdateUserAccountDetailsPage
from pages.Users.user_information_page import UserInformationPage
from pages.Users.user_assignments_page import UserAssignmentsPage

from pages.Users.manage_permissions_page import ManagePermissionPage
from pages.Users.create_permission_page import CreatePermissionPage

from pages.Users.manage_roles_page import ManageRolesPage
from pages.Users.create_role_page import CreateRolePage

from pages.Partners.manage_partners_page import ManagePartnersPage
from pages.Partners.create_partner_page import CreatePartnerPage

from pages.Products.create_product_page import CreateProductPage
from pages.Products.manage_products_page import ManageProductsPage
from pages.Products.view_product_page import ViewProductPage

from pages.Pages.manage_pages_page import ManagePagesPage
from pages.Pages.create_page_page import CreatePagePage
from pages.Pages.additional_page_page import AdditionalPagePage
from pages.Pages.site_page_page import SitePagePage
from pages.Pages.parent_page_page import ParentPagePage

from pages.Inventorygroups.manage_inventory_groups_page import ManageInventorygroupsPage
