from .main_page import MainPage
from .login_page import LoginPage
from .manage_users_page import ManageUsersPage
from .create_user_page import CreateUserPage
from .update_user_page import UpdateUserPage
from .create_product_page import CreateProductPage
from .view_product_page import ViewProductPage
from .manage_products_page import ManageProductsPage
from .manage_partners_page import ManagePartnersPage